import dallemini from "#api/dalle-mini.js";
import { Command } from "Interfaces";

export const command: Command = {
  name: "dallemini",
  description: "Generate images from text",
  aliases: ["dalle"],
  args: true,
  usage: "...<prompt>",
  examples: [ "harry potter with a sword"],
  roleAccess: "betaTesters",
  async run({msg,content}){
    const m = await msg.reply(`${msg.client.config.emojis.rollCat} Fetching...\n> *it may take a while.*`);
    dallemini(content())
      .then(files=>{m.edit({
        content: "Generated by Dall-e Mini:",
        files
      })})
      .catch(()=>{
        msg.edit("Failed to fetch.")
      })
  }
}
