import { argumentObjectType} from '../types';
import insp from '#api/inspirobot.js';

export default {
  name : 'inspire',
  description : 'Quotes generated by InspiroBot',
  aliases : ['insp'],
  //usage : '[...query]',
  //args : true,
  // permissions : string,
  //devOnly : true,
  // permRequired : [string],
  // examples : [''],
  run
}

function run({msg}:argumentObjectType){
  insp()
    .then(t=>msg.reply(t))
    .catch(()=>msg.reply(global.config.emojis.sad+' An Unknown Error Occurred while fetching from api.'))
}

