import insp from '#api/inspirobot.js';
import {Command} from 'Interfaces';

export const command : Command= {
  name : 'quote',
  description : 'Quotes generated by InspiroBot',
  aliases : ['insp'],
  run({msg}){
    insp()
      .then(t=>msg.reply(t))
      .catch(()=>msg.reply(msg.client.config.emojis.sad+' An Unknown Error Occurred while fetching from api.'))
    }
}

